### ISSUE TITLE
和element其他组件（DatePicker 日期选择器）使用时，会相互影响

### ISSUE THREAD

**Issue by AprilTong** [vincentzyc/byte-weektime-picker#1]
![image](https://user-images.githubusercontent.com/24354441/77387999-e79e8080-6dc9-11ea-9c86-66bc9d1ec0ba.png)
如图所示：
1.上面是一个elment的DatePicker 日期选择器
2. 下面使用的该插件
当我选择日期的时候，该事件不能触发，但是会触发byte-weektime-picker的点击事件

**Comment by AprilTong** [comment]
> ![image](https://user-images.githubusercontent.com/24354441/77387999-e79e8080-6dc9-11ea-9c86-66bc9d1ec0ba.png)
> 如图所示：
> 1.上面是一个elment的DatePicker 日期选择器
> 2. 下面使用的该插件
> 当我选择日期的时候，该事件不能触发，但是会触发byte-weektime-picker的点击事件

已经解决：
z-index 冲突导致

**Comment by vincentzyc** [comment]
> > ![image](https://user-images.githubusercontent.com/24354441/77387999-e79e8080-6dc9-11ea-9c86-66bc9d1ec0ba.png)
> > 如图所示：
> > 1.上面是一个elment的DatePicker 日期选择器
> > 2. 下面使用的该插件
> > 当我选择日期的时候，该事件不能触发，但是会触发byte-weektime-picker的点击事件
> 
> 已经解决：
> z-index 冲突导致

不好意思，现在才看到。
感谢使用，相互学习，谢谢支持
